const fields = [
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cybersecurity",
    "Web Development",
    "Mobile Development",
    "Cloud Computing",
    "Internet of Things (IoT)",
    "Blockchain",
    "Game Development",
    "Software Engineering",
    "DevOps",
    "Big Data",
    "Computer Vision",
    "Natural Language Processing",
    "Robotics",
    "Augmented Reality",
    "Virtual Reality",
    "Quantum Computing",
    "Bioinformatics",
    "Embedded Systems",
    "Network Security",
    "Database Management",
    "Human-Computer Interaction",
    "Operating Systems",
    "Distributed Systems",
    "Computer Graphics",
    "Algorithm Design",
    "Parallel Computing",
    "Cryptography",
    "Information Retrieval",
    "Software Testing",
    "Systems Programming",
    "Compiler Design",
    "Digital Signal Processing",
    "Artificial Neural Networks",
    "Reinforcement Learning",
    "Edge Computing",
    "Wearable Technology",
    "Smart Cities",
    "E-commerce Development",
    "Social Media Analytics",
    "Health Informatics",
    "Educational Technology",
    "Financial Technology (FinTech)",
    "Autonomous Vehicles",
    "Speech Recognition",
    "Image Processing",
    "Sensor Networks",
    "Augmented Analytics",
    "Predictive Analytics"
  ];
  
  export default fields;